### ISSUE TITLE
Not functional at all.

### ISSUE THREAD

**Issue by Kvothe-The-Bloodless** [ashaherb/Wiley-Downloader#3]
I just want to make it clear for anyone who comes across this. The bug mentioned in the other "Issue" is still there and makes this completely non-functional.

Error: bs4.FeatureNotFound on any usage.

**Comment by Kvothe-The-Bloodless** [comment]
Actually, attempted to solve it with `pip install lxml` but it just means you get stuck at the next error:

```
Traceback (most recent call last):
  File "scraper.py", line 22, in <module>
    title_text = ''.join(title.findAll(text=True))
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by areyoufeelingitnowmrkrebs** [comment]
> Actually, attempted to solve it with `pip install lxml` but it just means you get stuck at the next error:
> 
> ```
> Traceback (most recent call last):
>   File "scraper.py", line 22, in <module>
>     title_text = ''.join(title.findAll(text=True))
> AttributeError: 'NoneType' object has no attribute 'findAll'
> ```

I was able to work around this by simply specifying `title_text="Title of Book"` which lead to a "successful" download, however the pdf wouldn't open in my pdf viewer and threw some kind of error about it being corrupted.
